import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProviderClient } from "@/components/providers/theme-provider.client";
import { AuthProviderClient } from "@/components/providers/auth/auth-provider.client";
import { QueryProviderClient } from "@/components/providers/query-provider.client";
import { Header } from "@/components/header";
import { GraphqlProvider } from "@/components/providers/graphql-provider.client";
import { Sidebar } from "@/components/sidebar";
import SidebarProvider from "@/components/providers/sidebar-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-muted/40 font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProviderClient
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <GraphqlProvider>
            <QueryProviderClient>
              <AuthProviderClient>
                <div className="min-h-screen flex flex-col">{children}</div>
              </AuthProviderClient>
            </QueryProviderClient>
          </GraphqlProvider>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
