version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - ${DB_PORT}
    volumes:
      - ./db/postgresql.conf:/etc/postgresql/custom-postgresql.conf
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/custom-postgresql.conf
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
  db2search:
    build:
      context: ./db2search
    restart: always
    depends_on:
      - db
      - search
    volumes:
      - ./db2search/src:/app/src
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
      ELASTICSEARCH_HOST: search
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
    command: ["sh", "-c", "air"]
