version: '3.9'

services:
  db:
    image: postgres:14.7
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - ${DB_PORT}
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${API_GATEWAY_APP_PORT}:${API_GATEWAY_APP_PORT}"
    expose:
      - ${WEB_PORT}
      - ${AUTH_SERVICE_PORT}
      - ${CORE_SERVICE_PORT}
    depends_on:
      - db
    command: yarn start:demo
    environment:
      API_GATEWAY_APP_PORT: ${API_GATEWAY_APP_PORT}
    volumes:
      - ./apps/server/apps:/usr/src/app/apps/server/apps
      - ./apps/server/libs:/usr/src/app/apps/server/libs
      - ./apps/web-ssr/src:/usr/src/app/apps/web-ssr/src
